name: Docker Image CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get the git tag
      id: get_tag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag icomputerfreak/foundry-world-switcher:${{ steps.get_tag.outputs.tag }} --tag icomputerfreak/foundry-world-switcher:latest
        docker build . --file DockerfilePterodactyl --tag icomputerfreak/foundry-world-switcher:${{ steps.get_tag.outputs.tag }}-pterodactyl --tag icomputerfreak/foundry-world-switcher:pterodactyl

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push the Docker image to Docker Hub
      run: |
        docker push icomputerfreak/foundry-world-switcher:${{ steps.get_tag.outputs.tag }}
        docker push icomputerfreak/foundry-world-switcher:latest
        docker push icomputerfreak/foundry-world-switcher:${{ steps.get_tag.outputs.tag }}-pterodactyl
        docker push icomputerfreak/foundry-world-switcher:pterodactyl
