name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get the git tag
      id: get_tag
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag foundry-world-switcher:${{ steps.get_tag.outputs.tag }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Tag the Docker image as latest
      run: docker tag foundry-world-switcher:${{ steps.get_tag.outputs.tag }} foundry-world-switcher:latest

    - name: Push the Docker image to Docker Hub
      run: |
        docker push icomputerfreak/foundry-world-switcher:${{ steps.get_tag.outputs.tag }}
        docker push icomputerfreak/foundry-world-switcher:latest
